### ISSUE TITLE
Share buttons on detail page have to be styled cross-browser-compatible

### ISSUE THREAD

**Issue by marians** [okfn/yourtopia#26]
Currently they don't appear correct in Safari and Firefox.

**Comment by marians** [comment]
Closing, as I'm not working on this project any longer.

**Comment by rufuspollock** [comment]
@marians but was it actually fixed? If not, could you just unassign yourself 😉

**Comment by marians** [comment]
@rufuspollock I can't unassign myself, as I am no longer in the okfn org.

Don't know if the issue is fixed. Currently I can't even find the app online. If you want to re-open, please un-assign me. Thanks!
